# Generated by Django 4.1.3 on 2023-11-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="month",
            field=models.CharField(max_length=100),
        ),
    ]
